
APPLICATION_NAME_WIDGET = "APPLICATION_NAME_WIDGET"
TIER_LEVEL_DROPDOWN_WIDGET = "TIER_LEVEL_DROPDOWN_WIDGET"
GET_ANSWER_WIDGET = "GET_ANSWER_WIDGET"


ARCH_HLD_FILE_SELECTOR_WIDGET = "ARCH_HLD_FILE_SELECTOR_WIDGET"
DR_PLAN_PROCEDURE_SELECTOR_WIDGET = "DR_PLAN_PROCEDURE_SELECTOR_WIDGET"
DR_TEST_TTX_FILE_SELECTOR_WIDGET = "DR_TEST_TTX_FILE_SELECTOR_WIDGET"
RCA_REPORTS_FILE_SELECTOR_WIDGET = "RCA_REPORTS_FILE_SELECTOR_WIDGET"
MONITORING_DASHBOARDS_FILE_SELECTOR_WIDGET = "MONITORING_DASHBOARDS_FILE_SELECTOR_WIDGET"
BACKUP_SETTINGS_REPORTS_FILE_SELECTOR_WIDGET = "BACKUP_SETTINGS_REPORTS_FILE_SELECTOR_WIDGET"
PRIOR_PATTERN_STANDARDS_FILE_SELECTOR_WIDGET = "PRIOR_PATTERN_STANDARDS_FILE_SELECTOR_WIDGET"




# DATA

OPEN_AI_API_KEY_DATA = "OPEN_AI_API_KEY_DATA"
RESPONSE_DATA = "RESPONSE_DATA"


# OBJ

OPEN_AI_CLIENT_OBJ = "OPEN_AI_CLIENT_OBJ"